// <auto-generated />
namespace PcComponentsShop.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PaidAtField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PaidAtField));
        
        string IMigrationMetadata.Id
        {
            get { return "201910201405088_PaidAtField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
